services:

  local-db:
    container_name: local-3phi-db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 3phi-db
    ports:
      - "5432:5432"
    volumes:
     - ./tmp/pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d 3phi-db -h 127.0.0.1"]
      interval: 2s
      timeout: 5s
      retries: 60
      start_period: 10s

  sqitch-runner:
    container_name: local-3phi-sqitch
    image: sqitch/sqitch
    working_dir: /sqitch
    environment:
      DB_HOST: local-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: 3phi-db
      ROLE: threephi_db_user
      ROLE_PW: userpass
    depends_on:
      local-db:
        condition: service_healthy
    volumes:
      - ./.migrations/sqitch:/sqitch
    entrypoint: ["bash", "-lc"]
    command: >
      "bash ./create-db-user.sh $${DB_HOST} $${DB_PORT} $${DB_USER} $${DB_PASSWORD} $${ROLE} $${ROLE_PW} $${DB_NAME}
      && bash ./sqitch-deploy.sh $${DB_HOST}:$${DB_PORT} $${DB_USER} $${DB_PASSWORD} $${DB_NAME}"
    restart: "no"

  local-object-storage:
    container_name: local-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./object_storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
